import type { Metadata } from "next";
import { Inter as FontSans, Kaisei_Decol as FontKai } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/Navigation";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// Font files can be colocated inside of `pages`
const fontKai = FontKai({
  subsets: ["latin"],
  variable: "--font-kai",
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* default Inter font */}
      <body
        className={cn(
          "bg-zinc-900 text-white",
          fontSans.variable,
          fontKai.variable
        )}
      >
        <Navigation />
        <main className="lt-xs:px-4 px-8 max-w-5xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
